"""tools, assistants_tools

Revision ID: 0a19d73518f3
Revises: 0f2e4605e415
Create Date: 2024-06-10 02:43:34.581478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a19d73518f3'
down_revision: Union[str, None] = '0f2e4605e415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tools',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('src', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sync', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assistants_tools',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('assistant_name', sa.INTEGER(), nullable=False),
    sa.Column('tool_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['assistant_name'], ['assistants.name'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('assistants_aid_key', 'assistants', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('assistants_aid_key', 'assistants', ['aid'])
    op.drop_table('assistants_tools')
    op.drop_table('tools')
    # ### end Alembic commands ###
