"""fixes

Revision ID: 26d972005194
Revises: be2270eabf14
Create Date: 2024-06-15 14:37:10.509967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26d972005194'
down_revision: Union[str, None] = 'be2270eabf14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'fid',
               existing_type=sa.INTEGER(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('files', 'name',
               existing_type=sa.INTEGER(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'name',
               existing_type=sa.TEXT(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('files', 'fid',
               existing_type=sa.TEXT(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
