"""nullable fixes

Revision ID: be2270eabf14
Revises: 5dc771eb1a33
Create Date: 2024-06-15 14:14:26.365854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be2270eabf14'
down_revision: Union[str, None] = '5dc771eb1a33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vector_stores', 'vsid',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vector_stores', 'vsid',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
