"""assisstant.aid missdeleted

Revision ID: f92e58c5fac3
Revises: f4e199d5c74e
Create Date: 2024-06-11 03:15:36.314826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f92e58c5fac3'
down_revision: Union[str, None] = 'f4e199d5c74e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('aid', sa.TEXT(), nullable=True))
    op.create_unique_constraint(None, 'assistants', ['aid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assistants', type_='unique')
    op.drop_column('assistants', 'aid')
    # ### end Alembic commands ###
